name: staff_manager
version: 1.0.0+1
publish_to: none
description: A Flutter project for Managing Staff Details.
environment: 
  sdk: '>=2.18.2 <3.0.0'

dependencies: 
  flutter: 
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_nav_bar: ^5.0.6
  image_picker: ^0.8.6

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

